package org.mcv.mu;

public enum Keyword implements TokenType {
	NONE,
	IMPORT, FROM, AS, WHERE,
	TYPE, CLASS, OPERATOR,
	UNIT, SIUNIT,
	FUN,
	RETURN,
	THROW,
	PRINT, ASSERT,
	VAR, VAL, GET, // SET,
	IF, UNLESS, ELSE,
	SELECT, WHEN,
	DO, WHILE, UNTIL,
	BEFORE, AFTER, AROUND, ERROR, ALWAYS,
	FOR, IN,
	BREAK, CONTINUE,
	FALSE, TRUE, NIL,
	SQRT, ABS, XOR,
	MOD, REM, INF, NAN,
	// type operators
	REF, LIST, SET, MAP, ENUM
}
