package org.mcv.mu;

public enum Keyword implements TokenType {
	NONE,
	MODULE, IMPORT,
	TYPE, TYPEOF, CLASS, INTERFACE,
	FUN,
	RETURN,
	PRINT,
	VAR, VAL, 
	IF, UNLESS, ELSE,
	SELECT, WHEN,
	DO, WHILE, UNTIL,
	BEFORE, AFTER, AROUND, ERROR, ALWAYS,
	FOR, IN,
	BREAK, CONTINUE,
	FALSE, TRUE, NIL,
	SQRT, GCD, ABS, MAX, MIN, XOR,
	MOD, REM, INF, NAN,
	// type operators
	REF, LIST, SET, MAP, ENUM
}
