package org.mcv.mu;

enum Soperator implements TokenType {
	NONE,
	// Single-character tokens.
	LEFT_PAREN, LPAREN_CALL, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRK, RIGHT_BRK, BACKTICK, /* APOSTROPHE, DBLQUOTE */
	ATSIGN, SHARP, PERCENT, POW, BACKSLASH, QUESTION, BANG, DOLLAR, UNDERSCORE,
	COMMA, DOT, MINUS, PLUS, COLON, SEMICOLON, SLASH, STAR, AND, OR, EMPTY_SET, UPARROW,
	// specials
	NEWLINE, INDENT, DEDENT,
	// One or two character tokens.
	NOT, NOT_EQUAL, ASSIGN, EQUAL, EQEQ, NEQEQ, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, ARROW, 
	LEFTSHIFT, RIGHTSHIFT, PLUSPLUS, MINMIN, DOTDOT, 
	PLUSIS, MINIS, STARIS, SLASHIS, POWIS, XORIS, PERCENTIS, ANDIS, ORIS, LSHIFTIS, RSHIFTIS,
	OPERATOR, SAFENAV, SAFESUB, SAFECALL,
	// Literal types
	ID, TID, STRING, RSTRING, CHAR, REAL, INT, UNITLIT,
	// EOF
	EOF
}