package org.mcv.mu;

enum Soperator implements TokenType {
	NONE,
	// Single-character tokens.
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_BRK, RIGHT_BRK, BACKTICK, /* APOSTROPHE, DBLQUOTE */
	ATSIGN, SHARP, DOLLAR, PERCENT, POW, XOR, BACKSLASH, UNDERSCORE, QUESTION, BANG, 
	COMMA, DOT, MINUS, PLUS, COLON, SEMICOLON, SLASH, STAR, AND, OR, EMPTY_SET,
	// One or two character tokens.
	NOT, NOT_EQUAL, ASSIGN, EQUAL, EQEQ, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, ARROW, 
	LEFTSHIFT, RIGHTSHIFT, PLUSPLUS, MINMIN, DOTDOT, 
	PLUSIS, MINIS, STARIS, SLASHIS, POWIS, XORIS, PERCENTIS, ANDIS, ORIS, LSHIFTIS, RSHIFTIS,
	/* ELVIS, SPACESHIP, ... */
	// Literal types
	ID, TID, STRING, CHAR, REAL, INT, 
	// EOF
	EOF
}